import { cookies } from "next/headers";
import { Session } from "next-auth";
import { auth } from "./api/auth/[...nextauth]/route";
import type { Metadata} from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";;
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inga next",
  description: "Generated by create next app and posgresql",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const cookieStore = cookies();

  return (
    <html lang="en">
        <body className={`${cookieStore.get("theme")?.value ||  "light"} text-base md:text-lg ${inter.className}`}>
          <div className="bg-gradient-to-t from-cyan-500 to-blue-500 dark:from-sky-700 dark:to-indigo-900 text-gray-900 dark:text-white">
              <Header themeProp={`${cookieStore.get("theme")?.value == 'dark'? 'dark' :  "light" }`} SessionProp={session as Session} />
              {children}
              <Footer />
          </div>
        </body>
    </html>
  );
}
